version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'build'
    labels:
      - 'comp: build & ci'
      - 'target: patch'
      - 'action: merge'
